### PR TITLE
Added DIN 96 wood screw

### PR DESCRIPTION
**Pull request by berberic2**
DIN 96: Halbrund-Holzschrauben mit Schlitz

works for me. 
Maybe you should check if it conforms to the “style-guide” of the refactoring.
Screenshot_20221001_232111

### CODE REVIEW

**Comment by shaise** [comment]
Thanks a lot! It is definitely conforms to the new style.

**Comment by FreeCAD-Tools** [comment]
@berberic2 Good work!
Can you add DIN 7996 ?
These fasteners are almost similar. The difference is only in the cross slot.

**Comment by FreeCAD-Tools** [comment]
It looks strange, but the din571 tables that are now exists in the master branch correspond to din 96...

**Comment by berberic2** [comment]
There are some typos…

d3 is the core diameter of the thread (see https://online-schrauben.de/shop/Gewindearten-Holzschrauben-Gewinde-DIN-7998?chapter=3)

k seems to be always equal to d3, but as far as I can determine this is correct for DIN 96.

din96length.csv actually is a copy from din571length.csv because I could not find this data.

**Comment by FreeCAD-Tools** [comment]
> din96length.csv actually is a copy from din571length.csv because I could not find this data.

Try searching through the Russian version of Google....

**Comment by FreeCAD-Tools** [comment]
You refuse in vain. There are a lot of interesting things there.

**Comment by FreeCAD-Tools** [comment]
At the expense of d3, everything became clear.

**Comment by FreeCAD-Tools** [comment]
The length table is used when generated thread? Or is it added just for reference?

**Comment by berberic2** [comment]
It is not used in generating the screw-objects at all.
I don’t know what it is for.

**Comment by shaise** [comment]
it is legacy data, and sort of place holder for the dictionary should new data will be needed in the future

**Comment by FreeCAD-Tools** [comment]
@berberic2
On DIN 96 is possible to create DIN 7971.
Only need to stretch the thread to the entire diameter.

Does anyone mind if you create a universal function for several types of fasteners based on the din96 function?

**Comment by FreeCAD-Tools** [comment]
Maybe add new FastenerType("WoodScrew")?

**Pull request merged**
