### PR TITLE
added DIN 571 hex wood screws

### PR DESCRIPTION
**Pull request by berberic2**
This adds wood-screws with hexagon head (DIN 571 Sechskant-Holzschrauben).

The model is simplified without the DIN 7998 threads, so the thread property does not work.
(see https://forum.freecadweb.org/viewtopic.php?p=608972)

### CODE REVIEW

**Comment by shaise** [comment]
The thread parameter is not functional. I guess this is because its a special wood thread, we do not have code for, yet. I will mege it as is, though, so perhaps in the future we will add wood threads.

**Comment by berberic2** [comment]
Yes. The thread is defined in DIN 7998 and there is no code for this yet.
And its a bit complicated, because wood-screws have a tip with threads.
see: https://online-schrauben.de/shop/Gewindearten-Holzschrauben-Gewinde-DIN-7998?chapter=3

**Comment by luzpaz** [comment]
>  there is no code for this yet.

Do we want to notate this somewhere

**Comment by shaise** [comment]
I have added basic DIN7998 thread creation. it is not entirely accurate (mostly because of OCCT issues) but it is good enough.
Still in several diameter/length combinations the thread creation fails. If someone is familiar with OCCT quirks and can help fix, it will be great
image

**Comment by shaise** [comment]
in some cased the fusion of the thread with the body fails.

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.26155 (Git)
Build type: Release
Branch: master
Hash: 0926a4148bcff11249fd4f56bc30256102ffe105
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

**Comment by luzpaz** [comment]
@shaise can you open a ticket on master ? (or locate one)

**Comment by shaise** [comment]
this a very long time issue with OCC, there are many cases with slightly complex objects, that boolean operations does not work well.

**Comment by luzpaz** [comment]
Can you [link](https://github.com/FreeCAD/FreeCAD/issues?q=is%3Aopen+is%3Aissue+label%3A%223rd+Party%3A+OCC%22) to it?

**Comment by shaise** [comment]
I tried looking for something similar, but could not found.
I'm just used to this issue for years. It is mentioned quite often in the forum. In many cases I do small tweeks as adding epsilon to dimentions, and in most cases it works. here are examples in the forum:
https://forum.freecadweb.org/viewtopic.php?p=573261#p573261
https://forum.freecadweb.org/viewtopic.php?p=226514#p226514

**Pull request merged**
