### PR TITLE
Remove DIN1624 entry

### PR DESCRIPTION
**Pull request by hasecilu**
Previously DIN1624 was renamed on #329

### CODE REVIEW

**Comment by tobiasfalk** [comment]
That's curious, I have removed this Line in #329
But if it reappeared,than it should be removed

**Comment by hasecilu** [comment]
I think it got added again with pins merge

**Comment by shaise** [comment]
yes. I'm working a bit on the pins pr, and already removed this line. so this fix will be unnecessary after I finish.

**Comment by hasecilu** [comment]
ok, I'll close this.

**Pull request closed without merging**
