### PR TITLE
Add cross-recessed pan head tapping screws and slotted set screws

### LINKED ISSUE #74: Self Tapping Screws
Hello, 

I was trying to find these self-tapping screws that work really well with plastics.
For instance, size M2.6 that I need to use with a pointy tip. 

image

My reference is here.
https://www.amazon.com/Tapping-400Pcs-Screws-Assortment-Plastic/dp/B07VQZXGH2

Can you tell me if we have this in this workbench?
Also, if it is not there yet, is it possible to ask this as a feature request?

### PR DESCRIPTION
**Pull request by hasecilu**
- Minor fixes
- Add docstrings to get help
Screenshot_2023-12-22_12-14-54
- Add ISO1478: Tapping screws thread, needed to make the screws
- Add self tapping screws, based on Wood screws

~~I have some doubt about the tips, in the thread ISO there is the `y` val that sets the length of incomplete thread, it seems that in the original code there is no need for this parameter.
If someone want to review it to check there is nothing odd...~~  It  seems in the way the thread is made this value doesn't have an effect.
image
ArcoLinux_2024-01-02_19-15-36

image

Data from:
- https://cdn.standards.iteh.ai/samples/54046/cdf129d179c645d7b5c43390e21e0811/ISO-7049-2011.pdf
- https://cdn.standards.iteh.ai/samples/29386/1b1037055cc84afca508dc7b25917ccb/ISO-1478-1999.pdf
- https://cdn.standards.iteh.ai/samples/4098/cdc6edd80e0247fd8a85fb73dcc2fae6/ISO-225-1983.pdf

**Edit**: With the last `git push --force` I made other changes:
- Cleaned the self tapping code 
- Add ISO 86-1, ISO 86-2 and ISO 262, I make use of them in the `FSmakeSetScrew.py` file
- Add help on CONTRIBUTION guide
- Add 4 slotted set screws
- Remove duplicated icons, added to alias
- Fix a T-Slot nut bug

More changes:
- Add GN 506 T-slot nut
- Add ISO 2936 hex key

Fix #74

### CODE REVIEW

**Comment by shaise** [comment]
Wow, thats quite some work!

**Comment by hasecilu** [comment]
Now with `ISO262` we can replace `MetricPitchTable` instances.
I moved the set screws to their own group, hope this is a better organization, if not I can move them to slottted and Hcross groups.
I'll add 2-3 more fasteners and that would be for now.
image

**Comment by shaise** [comment]
sounds good!

**Comment by hasecilu** [comment]
Are magnets a good addition for Fasteners WB? Sometimes they are used to help when joining parts. I'm thinking in the neodymium small ones, square, rectangle, circle, ring shapes.

**Comment by hasecilu** [comment]
Well, I'll leave magnets for the library, I think this is ready unless review.

**Comment by shaise** [comment]
I did some tests and it looks great!
The only thing that troubles me is spaces in the "ST xx" designations. It seems to work fine but I prefer no spaces in designations and object names. Maybe use STxx or ST-xx? What do you think?
image

**Comment by hasecilu** [comment]
> I did some tests and it looks great! The only thing that troubles me is spaces in the "ST xx" designations. It seems to work fine but I prefer no spaces in designations and object names. Maybe use STxx or ST-xx? What do you think? 

I removed the space. I remember in some files had the space and in other don't. Commits fixed.
Also I spotted some string with no translation and marked them.

**Comment by shaise** [comment]
Hi @hasecilu ,

Thanks for this huge work!
It is also a good excuse to bump the version to 0.5.0...

**Pull request merged**
