### PR TITLE
Support for non-metric and custom sized thread cutting tools

### PR DESCRIPTION
**Pull request by alexneufeld**
to further address #64 
per request by @cfunseth

Thread cutting primitives (and the threaded rod object) can now have a 'Custom' diameter. If this option is set, the properties 'diameterCustom' and 'pitchCustom' will be used to generate geometry.

Property view with new parameters highlighted:

image

An M7 threaded rod with an unusual coarse pitch:
 
image

I also added inch versions of the threading tools (they create standard UNC threaded solids):

image

Inch versions of the commands have the 'Custom' diameter option as well. Note that when this property is set, the inch and metric versions behave the same (pitch and diameter is entirely the users responsibility!)

### CODE REVIEW

**Comment by cfunseth** [comment]
@alexneufeld Wow, thank you for implementing this so quickly!  I tested out your changes and everything looks to be working wonderfully!

One question/suggestion is regarding what "diameter Custom" defines?  Is this the pitch diameter, major diameter, or something else entirely?  I'm assuming it's pitch but I haven't been able to confirm yet. It may be beneficial to add this into the field description so future users know right off the bat. 

Again, thank you so much for adding this functionality!

**Comment by shaise** [comment]
@alexneufeld 
Thanks for the PR!
Can you please check backward compatibility before I merge. Save a file with an older FreeCad version (before your change) that contains a threaded rod.
Load the file with the new version, and try to change the diameter to custom. See if this works or at least does not generate any error. 
Thanks!

**Comment by cfunseth** [comment]
@shaise Using FreeCAD 0.19, I created an M8 ScrewTap with the older Fasteners workbench and saved it.  I then copied over the PR files, and opened the file again with the updated Fasteners workbench.  When I went to change the diameter, I did not see any Custom or pitchCustom options presented to me:
image

I can change the diameter of the existing M8 tap to any of the predefined sizes with no error.  Also, if I create a new ScrewTap with the updated workbench in the same file, then I am presented with the Custom and pitchCustom options which allow me to create a custom taps.

Hope this answers your question!

**Comment by alexneufeld** [comment]
> @alexneufeld Wow, thank you for implementing this so quickly! I tested out your changes in FreeCAD 0.19 and everything looks to be working wonderfully!
> 
> One question/suggestion is regarding what "diameter Custom" defines? Is this the pitch diameter, major diameter, or something else entirely? I'm assuming it's pitch but I haven't been able to confirm yet. It may be beneficial to add this into the field description so future users know right off the bat.
> 
> Again, thank you so much for adding this functionality!

FastenersWB is all based on the major diameter of the screw. Latest commit changes the property descriptions to reflect this.



> @alexneufeld
> Thanks for the PR!
> Can you please check backward compatibility before I merge. Save a file with an older FreeCad version (before your change) that contains a threaded rod.
> Load the file with the new version, and try to change the diameter to custom. See if this works or at least does not generate any error.
> Thanks!

I added a few lines to the `VerifyMissingAttrs` methods of the relevant objects to make sure the new properties are added to pre-existing document objects. Old objects will be brought in line with the latest features when they are recomputed.

**Comment by shaise** [comment]
> I added a few lines to the `VerifyMissingAttrs` methods of the relevant objects to make sure the new properties are added to pre-existing document objects. Old objects will be brought in line with the latest features when they are recomputed.

Great! and thanks!

**Pull request merged**
