### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by hasecilu**
Pretty sure it was OpenSCAD.

### CODE REVIEW

**Comment by hasecilu** [comment]
I use VNote to edit md files and with a single change in the table it gets re-accommodated in so way that the plain text looks like a table.

**Comment by shaise** [comment]
you are right about openSCAD, thanks.
but please undo the table, as we want github to handle the tabling automatically. (i.e if we have a standard longer then 23 chars, no need to rearrange the whole table)

**Comment by hasecilu** [comment]
I have reverted the table change.

**Comment by shaise** [comment]
Thank you!

**Pull request merged**
