### PR TITLE
Add pref entries to hide toolbar buttons by standard type

### PR DESCRIPTION
**Pull request by alexneufeld**
This is often requested by users who don't want the non-metric tool buttons cluttering up their FreeCAD UI.

image

### CODE REVIEW

**Comment by shaise** [comment]
Hi @alexneufeld ,
Thanks! I was thinking of doing a similar thing. 
The only thing that bothered me is that if occasionally you need a fastener from a hidden standard, you have to restart freecad for that. But I guess it is at least better than what we have now.

**Comment by luzpaz** [comment]
> The only thing that bothered me is that if occasionally you need a fastener from a hidden standard, you have to restart freecad for that. But I guess it is at least better than what we have now.

@shaise is there a working idea for a workaround ?

**Comment by shaise** [comment]
@luzpaz , I am not familiar with a way to add/remove toolbar buttons live. I need to see if maybe there is a way to have all the fasteners in the menu bar, and only the selected ones in the toolbar. this way, a fastener missing in the tool bar can always be found in the menu.

**Comment by shaise** [comment]
I think I have nice solution to my concern.
All the non showing fasteners can be still used by accessing the fasteners menu, under "Other"

image

**Comment by shaise** [comment]
just noticed a small bug with duplicated menus. Tending now.

**Comment by shaise** [comment]
fixed.

**Pull request merged**
