### PR TITLE
Add missing translations

### PR DESCRIPTION
**Pull request by riqueenz**

### CODE REVIEW

**Comment by riqueenz** [comment]
@shaise  The translation is complete. You can up the version if you want! Now it's time to write the documentation.
I also would like this translation to be added to the crowdin to the freecad-addons project to facilitate the translation into other languages. Maybe @yorikvanhavre can help me?

**Comment by shaise** [comment]
Great work! thanks.
Regarding crowdin I'm not familiar with. @luzpaz any idea who can help?

**Comment by FreeCAD-Tools** [comment]
@riqueenz Hi. Why utf-8 is not fully supported in main menu?
изображение

**Comment by FreeCAD-Tools** [comment]
And is possible to make name of workbench is translated?

https://github.com/shaise/FreeCAD_FastenersWB/blob/abbfc1d26ffe6ffa96bf106d9d3cdede0401a36b/InitGui.py#L38-L39

**Comment by riqueenz** [comment]
> And is possible to make name of workbench is translated?
> 
> https://github.com/shaise/FreeCAD_FastenersWB/blob/abbfc1d26ffe6ffa96bf106d9d3cdede0401a36b/InitGui.py#L38-L39

Yes, it is possible to translate the name of workbenches and tool tips. I think it's a good idea to translate the tooltips. But is it a good idea to translate the workbench name?

**Comment by riqueenz** [comment]
> @riqueenz Hi. Why utf-8 is not fully supported in main menu?
> 
> It seems to me that the error occurs due to combining strings with different encodings.
> 
> изображение

Yeah, I also had problems with utf8. I've been reading the FreeCad documentation about translations and localizations. But I still haven't found a solution.
https://wiki.freecadweb.org/Translating_an_external_workbench
https://wiki.freecadweb.org/Localisation

**Comment by FreeCAD-Tools** [comment]
> Great work! thanks. Regarding crowdin I'm not familiar with. @luzpaz any idea who can help?

@shaise Hi. I use Qt linguist tool.

изображение

Very convenient software. I think this should be enough for the first time. When the *.ts files are in complete condition, we can invite translators from the forum to github.

**Comment by FreeCAD-Tools** [comment]
> But is it a good idea to translate the workbench name?
@riqueenz I think yes. Sooner or later we will come to this. In Russian, this workbench sounds like (standard parts), because all parts In this workbench created by standards (ISO,DIN,EN etc..)

**Pull request merged**
