### PR TITLE
Add ASMEB18.6.1 wood screws

### PR DESCRIPTION
**Pull request by cfunseth**
Please take a look and let me know your thoughts! 

Wood screws seem unique as there is one function to handle them, but this ASME standard references two head styles. This contradicts how the rest of the workbench is laid out (functions based on screw head, not screw type), but I figured I'd keep them in the wood screw area until someone told me otherwise. Thankfully the countersunk and oval heads are so close that a lot of the code was common between them.

Related to https://github.com/shaise/FreeCAD_FastenersWB/issues/334

### CODE REVIEW

**Comment by cfunseth** [comment]
Also possibly related to https://github.com/shaise/FreeCAD_FastenersWB/issues/266

**Comment by hasecilu** [comment]
It's working fine, LGTM.

**Comment by shaise** [comment]
Thanks!
Just FIY - for #5 1/2 inch oval slotted wood screw, the thread fails. All other # seem to work

**Comment by cfunseth** [comment]
> Thanks! Just FIY - for #5 1/2 inch oval slotted wood screw, the thread fails. All other # seem to work

Whoops, it looks like I had an error in the #5 dimensions that was causing the thread to fail. I'll submit another PR that fixes that and some other issues I noticed.

**Comment by shaise** [comment]
Great work, Thanks!

**Pull request merged**
