### PR TITLE
Update of the translations in Polish and French

### PR DESCRIPTION
**Pull request by kaktusus**
A file update has been performed:
`fasteners_pl.qm`
`fasteners_pl.ts`
for the Polish language.

`fasteners_fr.qm`
`fasteners_fr.ts`
and French languages.
The translations for French were prepared by David69 from the FreeCAD forum.

### CODE REVIEW

**Comment by shaise** [comment]
Thanks!

**Comment by kaktusus** [comment]
I would like to ask you to notify the translators when an update is due. Not everyone pays attention if the changes affect the GUI.

If it's not a problem, could you post information about the update on the FC forum in the [translators section](https://forum.freecad.org/viewforum.php?style=4&f=45)  ?

**Comment by RoboticsNut** [comment]
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'translations/Fasteners_pl.qm'
  'translations/fasteners_pl.qm'

A quick diff showed that the two files are identical, is the one with the capital letter a mistake?

**Comment by kaktusus** [comment]
yes
`Fasteners_en.qm` can be removed.

**Comment by shaise** [comment]
Yes!!! finally!
For quite some time I was wondering why my git insists there is an issue, but I could not find what was it (As I use windows, and windows can not hold both files)

**Comment by kaktusus** [comment]
That was a file from the first translation edition. Later, I realized that the nomenclature in 'FastenersWB' is different from that in FreeCAD. But I forgot to delete this file. However, I can't explain why it's current

**Comment by shaise** [comment]
Anyway file is removed and my tortoise-git is all happy again :)

**Pull request merged**
