### PR TITLE
Update translation files

### PR DESCRIPTION
**Pull request by riqueenz**

### CODE REVIEW

**Comment by FreeCAD-Tools** [comment]
@riqueenz 

Hi, is possible to add FSprefs.ui translateable strings to all *.ts files.
More information at: https://github.com/shaise/FreeCAD_FastenersWB/issues/188

**Comment by FreeCAD-Tools** [comment]
@riqueenz 

Greet. Is possible to add translateable strings from  FSprefs.ui to all language *.ts files?
More information at: https://github.com/shaise/FreeCAD_FastenersWB/issues/188

**Comment by riqueenz** [comment]
> @riqueenz
> 
> Greet. Is possible to add translateable strings from FSprefs.ui to all language *.ts files? More information at: #188

A changed the create_ts.py script. However, I had problems joining the strings of the .ui and .py files. So I had to create separate translation files for each file type. #188

**Comment by shaise** [comment]
Thanks!

**Comment by FreeCAD-Tools** [comment]
@riqueenz
> However, I had problems joining the strings of the .ui and .py files. So I had to create separate translation files for each file type. #188

          # 3) Joining files
          os.system(
              """
              lconvert -i fasteners_es-ar.ts fasteners_uifiles_es-ar.ts -o fasteners_es-ar.ts
              #...code...
              lconvert -i fasteners_ru.ts fasteners_uifiles_ru.ts -o fasteners_ru.ts
              """
              )

Won't that help?

**Comment by FreeCAD-Tools** [comment]
@riqueenz
> However, I had problems joining the strings of the .ui and .py files. So I had to create separate translation files for each file type. #188

          # 3) Joining files
          os.system(
              """
              lconvert -i fasteners_uifiles_es-ar.ts fasteners_es-ar.ts -o fasteners_es-ar.ts
              #...code...
              lconvert -i fasteners_uifiles_ru.ts fasteners_ru.ts -o fasteners_ru.ts
              """
              )

Won't that help?

in lconvert command:
**fasteners_uifiles_es-ar.ts must be first after -i.**
**fasteners_es-ar.ts must be second after -i.**

I get normal results of join files:
[fasteners_ru.zip](https://github.com/shaise/FreeCAD_FastenersWB/files/9728499/fasteners_ru.zip)

The old translations have been preserved:
изображение

**Comment by FreeCAD-Tools** [comment]
I think this needs to be fixed since the data in: fasteners_uifiles_es-ar.ts and fasteners_es-ar.ts is duplicated...

**Comment by riqueenz** [comment]
> ```
>       # 3) Joining files
>       os.system(
>           """
>           lconvert -i fasteners_uifiles_es-ar.ts fasteners_es-ar.ts -o fasteners_es-ar.ts
>           #...code...
>           lconvert -i fasteners_uifiles_ru.ts fasteners_ru.ts -o fasteners_ru.ts
>           """
>           )
> ```
> 
> Won't that help?

I tried this on my computer and the translations done were overwritten with blank translations when I added more translate() functions in the code. I'll keep testing these commands over the next few days. I also aim to unify the translations into a single file for each language.

**Comment by riqueenz** [comment]
@FreeCAD-Tools

**Comment by FreeCAD-Tools** [comment]
@riqueenz

Did you exactly follow the sequence of files when calling the command?

in lconvert command:
fasteners_uifiles_es-ar.ts must be first after -i.
fasteners_es-ar.ts must be second after -i.

    lconvert -i fasteners_uifiles_es-ar.ts fasteners_es-ar.ts -o fasteners_es-ar.ts

You may try the reverse version:

    lconvert -i fasteners_es-ar.ts fasteners_uifiles_es-ar.ts -o fasteners_es-ar.ts

**Pull request merged**
