### PR TITLE
Add GN507 T slot nut

### PR DESCRIPTION
**Pull request by hasecilu**
A new T Slot nut, GN 507 T-slot nuts have been specially designed for use on extrusion rails.

I created a `TSlotNutParameters` and `TSlotGroup` to organize them.

Still don't have the slot width change working but I didn't see any bug with latest changes, so I think it can be merged.

Continuing #207

### CODE REVIEW

**Comment by shaise** [comment]
Hi @hasecilu 
There are some conflicts now after the last code cleanup. Please update and resolve conflicts.
Also, the parameter "slotWidth" has a different name under FastenerAttribs: "slotW". It should be the same name.
Thanks!

**Comment by shaise** [comment]
Thanks!!

**Comment by hasecilu** [comment]
>  Also, the parameter "slotWidth" has a different name under FastenerAttribs: "slotW". It should be the same name.

In line 67 is used `thicknessCode` and in line 74 `tcode` is used, then in L350 both names are used. Both `tcode` and `slotW` need change?
https://github.com/shaise/FreeCAD_FastenersWB/blob/b8a76a617a6d453a71d27e3b690185ea709558f2/FastenersCmd.py#L66-L74

https://github.com/shaise/FreeCAD_FastenersWB/blob/b8a76a617a6d453a71d27e3b690185ea709558f2/FastenersCmd.py#L350-L353

**Comment by EA32** [comment]
I try to make a join pull request, but this opportunity was blocked.
Icon optimized https://github.com/shaise/FreeCAD_FastenersWB/pull/233
Guide updated.
https://github.com/EA32/Guide-for-optimizing-SVG-icons-for-fasteners-workbench/blob/main/SVG_OPTIMIZATION_GUIDE.md

**Comment by hasecilu** [comment]
> Guide updated.

Cool!, I'll test next time

**Comment by shaise** [comment]
> In line 67 is used `thicknessCode` and in line 74 `tcode` is used, then in L350 both names are used. Both `tcode` and `slotW` need change?

Yes I prefer both being the same. However for backward compatibility, we will stay with `tcode` and `slotW`. If you decide to add a new parameter in the future, make them the same, and also as informative as possible: slotWidth is better then slotW.

**Pull request merged**
