### PR TITLE
[Fasteners] make slot generation based on screw head rather than just…

### PR DESCRIPTION
**Pull request by Syres916**
… an arbitrary size

Replaces https://github.com/shaise/FreeCAD_FastenersWB/pull/370

Tested successfully using OCC 7.5.3, 7.6.3 and 7.7.2

### CODE REVIEW

**Comment by shaise** [comment]
So why was it working with prev occ?

**Comment by Syres916** [comment]
I'll be honest my OCC knowledge isn't brilliant but it seems certain matrices fail with 7.7.x as per https://github.com/FreeCAD/FreeCAD/issues/9651
The previous slot cutter was particularly long at a metre in length in comparison to the screw heads which should have been fine anyway.

**Comment by shaise** [comment]
Meter in length... :)

**Comment by shaise** [comment]
Thanks!

**Pull request merged**
