### PR TITLE
Add ASMEB18.6.3.1Bdef

### PR DESCRIPTION
**Pull request by hasecilu**
Since ASMEB18.6.3.1B extends from ASMEB18.6.3.1A, the def should be there also.

Fix problem when `screwMaker.GetAllDiams(type)` was called.

Related #330

### CODE REVIEW

**Comment by cfunseth** [comment]
@hasecilu Just to make sure I'm understanding your reply, does this mean it would also be better to swap to `fa.dimtable` for this line as well? (It's what I based my code off since I didn't know any better)

https://github.com/shaise/FreeCAD_FastenersWB/blob/bbfc36bc5b6c0a338c5d087034630de14f507114/FsFunctions/FSmakeCountersunkHeadScrew.py#L61-L63

**Comment by hasecilu** [comment]
> @hasecilu Just to make sure I'm understanding your reply, does this mean it would also be better to swap to `fa.dimtable` for this line as well? (It's what I based my code off since I didn't know any better)

Yes, for better consistency across the project.

**Comment by cfunseth** [comment]
Thank you for all of your help!

**Comment by shaise** [comment]
Thanks!

**Pull request merged**
