### PR TITLE
Refactor csv2dict

### PR DESCRIPTION
**Pull request by elysium31**

### CODE REVIEW

**Comment by shaise** [comment]
can you explain why it is all under "test" directory, and test_utils? and why there aew empty files?
also what is the main purpose for rfactoring?

**Comment by elysium31** [comment]
That's the standard layout for tests. You can read about it here [https://docs.pytest.org/en/6.2.x/goodpractices.html](https://docs.pytest.org/en/6.2.x/goodpractices.html ). Particulary `__init__.py` files are needed to handle directories as modules, it is ok that they are empty.
I have created `tests_utlits` folder because I am going to add more tests on other functions.
The purpose was to shrink function `csv2dict` to a couple of lines, and remove unneeded operations like iteration over values.

**Comment by shaise** [comment]
Thanks for the clarification.
But why csv2dict is considered a test function? It is maybe a util function.

**Comment by luzpaz** [comment]
@elysium31 bump

**Comment by luzpaz** [comment]
> But why csv2dict is considered a test function? It is maybe a util function.

@elysium31 please clarify

**Comment by luzpaz** [comment]
@elysium31 ping

**Comment by elysium31** [comment]
Sorry, was bussy with war. I have moved the `csv2dict` function into `utils` module. (It is going to be, as you call it, "util function") The "test function" is `test_csv2dict` in tests/test_utils path. I suppose you mixed these two.

**Pull request merged**
