### PR TITLE
Update translation script

### PR DESCRIPTION
**Pull request by hasecilu**
The old script worked good enough but it was hard to read and also didn't follow the workflow (updated and released at the same time when in reality the changes of the translator should be in the middle, minor thing).

The new script:
- is based on the script avilable at freecad.workbench_starterkit template.
- is well documented and easy to read

The script updates `fasteners.ts` file every time any other translation file is created or updated. This is made with the objective of having this file updated with the most current changes. If a translator doesn't have access to `pylupdate` command it can start translating based on the `fasteners.ts` file, it only needs to replace
```xml
<TS version="2.1">
```

for

```xml
<TS version="2.1" language="it" sourcelanguage="en">
```

using their language code (must be supported on FreeCAD).

I tested both scripts and the generated files is the same.

### CODE REVIEW

**Comment by shaise** [comment]
Hi Ulices,

Thanks. However there are conflicts with `fasteners_es-es.ts` which I recently changed. 
can you update the changes?

shai

**Comment by hasecilu** [comment]
I made the changes. 

Notice that is not prossible to use custom functions to replace `translate()`, check my comment at https://github.com/alexneufeld/FreeCAD_FastenersWB/pull/1
This is the Spanish file, if you create a new file for another language it won't pick the strings that use `tr_cmd()`. So I restore them.
image

I'm even investigating why translations are not working on Assembly3 when using `QT_TRANSLATE_NOOP()` (which works on C++), at least worked some time ago...

**Comment by shaise** [comment]
hi Ulices,

one more small thing - all files should be lowercase. this will prevent possible collisions like we had before on windows systems.

shai

**Comment by hasecilu** [comment]
That's odd, could you test again?, also do you know if that happens with BIM WB, I see that WB also have uppercase letters, same as PieMenu or Assembly4 and haven't heard of something like that.

**Comment by shaise** [comment]
See issue #308.
It is indeed possible to use uppercase as well, however sometime someone misses, and we end with 2 files spelled the same just with different upper/lower case. This works fine on linux but causes issue on windows as it can not hold both files. So i decided that its best to have all files with same case, makes it easy to spot problems.

shai

**Comment by hasecilu** [comment]
I changed the script to save the file using lowercase.

**Comment by shaise** [comment]
thanks! this is great!

**Pull request merged**
