### PR TITLE
Update modification icons to be consistent with FreeCAD

### LINKED ISSUE #360: Update icons
I want to adjust some icons, not a complete overhaul to match stroke size and appearance of the modification tools of Fasteners WB (like BOM, move, flip,...).
Currently they are blue, the WB icon is green.
@shaise should I make the modification tool icons green like the WB icon or should they stay blue (or yellow like parts) and the WB icon also changed to blue (or yellow)?
grafik

### PR DESCRIPTION
**Pull request by maxwxyz**
fixes #360 
Following the discussion in the DWG I changed the modification icons to blue including the WB icon.
Color palette of imperial vs metric and maybe a general overhaul could follow later.
If merged, I'm also in favor of https://github.com/shaise/FreeCAD_FastenersWB/issues/307

grafik

### CODE REVIEW

**Comment by shaise** [comment]
Thanks!
These look great!
However I have a small issue: When all the icons become blue, it becomes increasingly harder to spot them at a glance when the icons are small. For example, with the old sheetmetal logo - it was ugly - but immediately spot-able when you glance on the toolbar.
As a designer, what do you think about it from the point of view of the user?

**Comment by hasecilu** [comment]
This looks awesome, same as in Sheet Metal WB.

Related question, did you know how to manipulate an svg on a Python WB? For example there are icons that are exactly the same and the only changes the color, one is metric and another is imperial.

Also, icons are color coded depending on if they are metric or imperial but there are various norms, so if it possible to manipulate we could assign to each norm a (similar) color. At the end SVG are just text but the current method to get the icons seems to get a rastered version of the icon...

**Comment by maxwxyz** [comment]
@shaise yes, the current insert fasteners are better with the smaller stroke and color, that's why I didn't change them. DWG might need to brainstorm what could be best for this. They currently do not look bad though, also if they are not using tango palette. I recently saw that the open color palette was mentioned in the design guide, but nothing complies currently.
And not all WB icons will be blue
grafik
Blue is for Part/PartDesign so bodies, that's why it makes sense to use them for features like sheetmetal/gears/fasteners too. FEM uses a lot of yellow icons, so it got a yellow touch. Mesh is green, Sketcher red, and so on. Optics just changed to a yellow beam like in the icons instead of a blue one. And I have a PR for Curved Shapes to get from blue to green result curves https://github.com/chbergmann/CurvedShapesWorkbench/pull/30 
Let me know if some are hard to distinguish, it can also be solved with a different shape.

@hasecilu There is a method in Sketcher WB, there is also a recent forum post: https://forum.freecad.org/viewtopic.php?t=86848
It's not just the color but ISO/ASME also look different. I'd prefer individual icons nothing hardcoded.

**Comment by shaise** [comment]
Thanks!

**Pull request merged**
