### PR TITLE
GOST1144-3-4 fastener integration

### PR DESCRIPTION
**Pull request by EA32**
image

### CODE REVIEW

**Comment by shaise** [comment]
Thanks!
Please note, I have moved these screws to the cross-recess group where they belong.

**Comment by EA32** [comment]
Fasteners moved https://github.com/shaise/FreeCAD_FastenersWB/pull/219

What about move all wood screws (because it have non metric/inch thread) to separate group?

**Comment by shaise** [comment]
I need to rethink the grouping anyway, since also metric/inch screws are mixed. I just do not want too many groups.

**Comment by EA32** [comment]
Ok.

**Pull request merged**
