### PR TITLE
 PCBSpacer.svg optimization

### PR DESCRIPTION
**Pull request by FreeCAD-Tools**
From 75kb to 1800bytes.

### CODE REVIEW

**Comment by shaise** [comment]
Thanks again!

**Comment by hasecilu** [comment]
Hi, what  option/process/program you use to optimize svg? The DIN508 file that I uploaded uses 108KB and I'm working in a new one that uses 120KB and both uses 11% of the whole folder. Maybe because I used thread in the icons?

**Comment by EA32** [comment]
@hasecilu

Hi. This begin of guide how to do that:
https://github.com/EA32/Guide-for-optimizing-SVG-icons-for-fasteners-workbench/blob/main/SVG_OPTIMIZATION_GUIDE.md

**Comment by shaise** [comment]
@FreeCAD-Tools
Thanks for the optimizing tips!

**Comment by hasecilu** [comment]
> DIN508 optimized to 2Kb. Don't forget the icon size should be 48x48 pixels. #228

Thanks, previously I tried to get the size with the `Export` option and not `Save as`, now I followed your guide and the new icon is "only" 52KB. Wow 2KB!

I think it would be useful if you made a PR to add your guide to the `CONTRIBUTING.md` file so anyone miss it.

**Pull request merged**
