### PR TITLE
unique designations per type in BOM

### LINKED ISSUE #319: [Feature request] Custom Designation string for each norm
An ISO norm typically states how the specified part should be designated, it would be nice if one could specify a template string in the function, so that the FreeCAD label is automatically in the norm designation form.
I was sadly not able to find one norm where a naming convention is specified, but the ISO and DIN norms all have a similar, if not identical, style. 

- ISO 8676: M12x1,5 l = 80mm "Festigkeitsklasse" 8.8 is a **Sechskantschraube ISO 8676 - M12 x 1,5 x 80 - 8.8**
- ISO 4032: Typ 1 d = M12  "Festigkeitsklasse" 8 is a **Sechskantmutter ISO 4032 - M12 - 8**
- DIN 961: M8x1 l = 50mm material assigned property class 8.8 is a **Hexagon head bolt DIN 961 - M8 x 1 x 50 - 8.8**
- DIN 961: M8x1 l = 50mm material assigned property class 8.8 product grade A is a **Hexagon head bolt DIN 961 - M8 x 1 x 50 - 8.8 - A**

Yes, the Material and a Production grade are mentioned in there. 
The material class could be created as a Parameter.
The grade is something that would need the "duplication" of some norms or another more complicated implementation, but this is another topic. (simply put many have multiple grades where the table would need to be done twice for some sizes, how one selected between two is not this issue)

### PR DESCRIPTION
**Pull request by alexneufeld**
The designation strings are taken directly from the associated fastener standard when possible.

### CODE REVIEW

**Comment by shaise** [comment]
Hi Alex,

Thanks for this update. 
However I have a few issues with it:
1. there is some kind of duplication having to add fasteners both in FastenersBillOfMaterial, and FastenersCmd
2. This causes also doubling of translations
3. Its not completely closes the issue since the user wanted to control the format of the line.

What I prefer is first separate the strings in the FastenersCmd so instead of: 
`"DIN571": (translate("FastenerCmd", "DIN 571 Hex head wood screw"), HexHeadGroup, ScrewParametersLC, "DIN"),`
do:
"DIN571": ("DIN 571", translate("FastenerCmd", "Hex head wood screw"), HexHeadGroup, ScrewParametersLC, "DIN"),
there is no need for the fastener code to part of the translatable string

and then we can use a format such as"
`"{description}, {code}, {dimension}"`
where dimension  is either diameter or diameter x length based on the type.
The format we can later put in the preferences window so the user can change it.
and this way the description will only be in the FastenersCmd file.

I can do the separation first if you like. I wanted to do it any way.

**Comment by alexneufeld** [comment]
That's fine with me. Here are the designation strings in spreadsheet form for your usage.
[designations.ods](https://github.com/shaise/FreeCAD_FastenersWB/files/14397281/designations.ods)

**Comment by shaise** [comment]
Thanks!
I'll let you know when finished.

**Comment by shaise** [comment]
Hi Alex,

Please take a look at my changes in FastenersCmd.py.
I left the original texts because they are more descriptive and they have already a translation. I just removed the code name from the string.

For the bom I suggest supporting the flowing format code names:  
`{description}` - take it from `FSScrewCommandTable[type][CMD_HELP]`  
`{shortdesc}` - take it from `FSScrewCommandTable[type][CMD_STD_GROUP]`  
`{code}` - take it from `FSGetTypePretty(type)`
`{dimension}` - dimension of fastener:  
    - before parsing this token send the format string to `FSUpdateFormatString(fmtstr, type)`  
    - this will replace the `{dimension}` token to either `{diameter}` or `{diameter} x {length}` based on the fastener type.  

for example to display the bom similar to your suggestion, use the format string:
`"{description}, {code}, {dimension}"`

shai

**Comment by hasecilu** [comment]
Hi, I see this is halted, I rebased this PR on master, made some fixes and added missing fasteners to BOM list here: https://github.com/hasecilu/FreeCAD_FastenersWB/tree/feat/designation_str

len(FSScrewCommandTable) -> 208
len(fasteners_designations) -> 204,       the 4 missing are: `FSScrewTapInch`, `FSScrewDieInch`, `FSScrewTap` and `FSScrewDie`, since these are not part of any norm and are helpers (for 3D printing?) should be tweak a little the colors to denote that fact? Related: since their main purpose is to use their thread, should the `thread` property be true by default?

Regarding the translation, it's true that if strings are changed they need to be translated twice but on Crowdin you have suggestions so the burden to translate again is not as bad.

**Pull request closed without merging**
