### PR TITLE
Added DIN 84 and DIN 934

### PR DESCRIPTION
**Pull request by tobiasfalk**
Added the old but still used DIN 84 and DIN 934  screw types, this standard is superseded by ISO 1207, ISO 4035 and ISO 8673, but for sices smaller than 1.6mm and size 1.8mm are not included and are often used and even sold sometimes even as ISO 1207 M1.4 for example.

### CODE REVIEW

**Comment by tobiasfalk** [comment]
What I also just found out is that auto size dous not work with hole sizes smaller than M1.6

**Comment by shaise** [comment]
Thank you for your contribution!
My only remark is that the new diameters use the comma notation (ie M20x1,5) but many other people uses the dot (ie M20x1.5). Of course this can not be changed automatically as other FreeCad tools, so we need to choose one of them.
@luzpaz What do you think?

**Comment by tobiasfalk** [comment]
@shaise I see what you mean and this is just do to the fact that I am used to it but I already chaged it so that it is in line with all the other fasteners and so.
I also changed the Min_Dia for DIN84 to M1 from M3.

**Comment by shaise** [comment]
Hi @tobiasfalk ,

Thanks for understanding and thanks again for this fine contribution!

shai

**Pull request merged**
