### PR TITLE
Update translation support

### PR DESCRIPTION
**Pull request by hasecilu**
I don't know why but translations stopped working. Anyway it was a opportunity to check to state of the translation support.

---

Now FreeCAD have support for Qt6, I don't know for how much time Qt5 will be around but the good thing is that we can use the tools from Qt6 and mainly I refer to `lupdate`.

> The previous way on which the files were updated is done is by creating
> some temporal files and then merging them to the original file.
> 
> Doing this merge would let us to NOT lost the translations already done.
> 
> It was done like that because we got the string from Python files and UI
> files because `lupdate` from Qt5 couldn't extract strings from Python
> files.
> 
> Now the `lupdate` from Qt6 can do, so we have no need to merge different
> temp files, instead, we can do the update in a single command.
> 
> The new advantage is that the `<location>` tag is updated with all new
> occurrences.

As  you can see in the script the command is greatly simplified.

Also updated the instructions on the README file.

Probably in the next days there is an update on translation files from CrowdIn so the WB will be ready to rock for 1.0 release 🤘.

### CODE REVIEW

**Comment by shaise** [comment]
@hasecilu ,

are you aware that all traslation is now done through Croudin?
From the file you have deleted:
image

**Comment by hasecilu** [comment]
> @hasecilu ,
> 
> are you aware that all traslation is now done through Croudin? From the file you have deleted: 

Yes, I know. I included it on the file that I moved:

image

If you think some instructions on the file should be renamed let me know.

**Comment by shaise** [comment]
Thanks!
Please move the `Translators` section to the top. Most of the users are translators and not maintainers and if I missed that, they might too. Also include the link, for those who are unfamiliar with Crowdin.
Thank you!
shai

**Comment by hasecilu** [comment]
Done

**Comment by shaise** [comment]
Thanks!

**Pull request merged**
